---
collections:
  - name: ansible.utils
  - name: ansible.core
  - name: community.general
  - name: ansible.posix
  - name: Community.docker
  - name: community.kubernetes
  - name: community.helm
  - name: community.general.proxmox_kvm