---
- name: Get Bootstrap Password from Rancher Container
  hosts: ranchers  # Điều này có thể thay đổi tùy thuộc vào cấu hình inventory của bạn
  gather_facts: no

  tasks:
    - name: Get container facts
      community.docker.docker_container_info:
        name:  recursing_haibt
      register: result

    - name: Does container exist
      ansible.builtin.debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Print info
      ansible.builtin.debug:
        var: result.container
      when: result.exists
