---
- name: Triển khai Rook Ceph trên Kubernetes
  hosts: servers
  become: yes
  tasks:
#     - name: Clone repository Rook
#       ansible.builtin.git:
#         repo: https://github.com/rook/rook.git
#         dest: /home/tctin/rook
#         version: v1.14.6
#         single_branch: yes

#     - name: Khởi tạo rook-ceph operator
#       ansible.builtin.shell:
#         cmd: kubectl create -f crds.yaml -f common.yaml -f operator.yaml
#         chdir: /home/tctin/rook/deploy/examples
#       environment:
#         KUBECONFIG: /home/tctin/.kube/config

#     - name: Kiểm tra trạng thái của pod rook-ceph-operator
#       ansible.builtin.shell:
#         cmd: kubectl get pods -n rook-ceph -l app=rook-ceph-operator -o jsonpath='{.items[0].status.phase}'
#       register: operator_status
#       retries: 6
#       delay: 40
#       until: operator_status.stdout == "Running"
#       environment:
#         KUBECONFIG: /home/tctin/.kube/config

#     - name: Tạo rook-ceph cluster nếu pod rook-ceph-operator đang chạy
#       ansible.builtin.command:
#         cmd: kubectl create -f cluster.yaml
#         chdir: /home/tctin/rook/deploy/examples
#       when: operator_status.stdout == "Running"
#       environment:
#         KUBECONFIG: /home/tctin/.kube/config

      - name: Kiểm tra trạng thái của các node Kubernetes
        ansible.builtin.shell:
          cmd: kubectl get nodes -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}' | grep -q "False"
        register: kubernetes_status
        retries: 3
        delay: 15
        until: kubernetes_status.rc != 0
        environment:
          KUBECONFIG: /home/{{ ansible_user }}/.kube/config

      - name: Clone repository Rook
        ansible.builtin.git:
          repo: https://github.com/rook/rook.git
          dest: "/home/{{ ansible_user }}/rook"
          version: v1.14.6
          single_branch: yes
        retries: 3
        delay: 20
        when: kubernetes_status.rc == 0  # Chỉ chạy khi tất cả các node đều ở trạng thái "Ready"

      - name: Khởi tạo rook-ceph operator
        ansible.builtin.shell:
          cmd: kubectl create -f crds.yaml -f common.yaml -f operator.yaml
          chdir: "/home/{{ ansible_user }}/rook/deploy/examples"
        environment:
          KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
        when: kubernetes_status.rc == 0  # Chỉ chạy khi tất cả các node đều ở trạng thái "Ready"

      - name: Kiểm tra trạng thái của pod rook-ceph-operator
        ansible.builtin.shell:
          cmd: kubectl get pods -n rook-ceph -l app=rook-ceph-operator -o jsonpath='{.items[0].status.phase}'
        register: operator_status
        retries: 6
        delay: 40
        until: operator_status.stdout == "Running"
        environment:
          KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
        when: kubernetes_status.rc == 0  # Chỉ chạy khi tất cả các node đều ở trạng thái "Ready"

      - name: Tạo rook-ceph cluster nếu pod rook-ceph-operator đang chạy
        ansible.builtin.command:
          cmd: kubectl create -f cluster.yaml
          chdir: "/home/{{ ansible_user }}/rook/deploy/examples"
        when: operator_status.stdout == "Running" and kubernetes_status.rc == 0  # Chỉ chạy khi pod đang chạy và tất cả các node đều ở trạng thái "Ready"
        environment:
          KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
