- name: Update all nodes
  hosts: servers, workers
  gather_facts: true
  become: yes
  roles:
    - role: update-nodes
    - role: prepare-nodes
    - role: install-containerd
    - role: install-environment

- name: Initialize Kubernetes cluster
  hosts: servers
  gather_facts: true
  become: yes
  roles:
    - role: init-cluster

- name: Fetch join command
  hosts: servers
  gather_facts: true
  become: yes
  roles:
    - role: fetch-joincommand

- name: Add worker nodes to cluster
  hosts: workers
  gather_facts: true
  become: yes
  roles:
    - role: add-workernodes
