- name: Update all nodes
  hosts: servers, workers
  gather_facts: true
  roles:
    - role: update-nodes

- name: Prepare all nodes
  hosts: servers, workers
  gather_facts: true
  roles:
    - role: prepare-nodes

- name: Install containerd
  hosts: servers, workers
  gather_facts: true
  roles:
    - role: install-containerd

- name: Install environment kubectl
  hosts: servers, workers
  gather_facts: true
  roles:
    - role: install-environment

- name: Initialize Kubernetes cluster
  hosts: servers
  gather_facts: true
  roles:
    - role: init-cluster

- name: Fetch join command
  hosts: servers
  gather_facts: true
  roles:
    - role: fetch-joincommand

- name: Add worker nodes to cluster
  hosts: workers
  gather_facts: true
  roles:
    - role: add-workernodes
