---
- name: Copy SSH key to remote hosts
  hosts: all
  become: yes
  tasks:
    - name: Ensure SSH directory exists
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Copy SSH public key to remote hosts
      ansible.builtin.copy:
        content: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        dest: ~/.ssh/authorized_keys
        mode: '0600'
      delegate_to: "{{ inventory_hostname }}"
      ignore_errors: yes
