- name: Read join command from master
  ansible.builtin.slurp:
    src: "/home/{{ ansible_user }}/join_command.txt"
  register: join_command_slurp

- name: Set join command fact
  ansible.builtin.set_fact:
    join_command: "{{ join_command_slurp.content | b64decode | trim }}"

- name: Join the node to Kubernetes cluster
  ansible.builtin.shell:
    cmd: "{{ join_command }}"
