- name: Update apt cache and upgrade all packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    force_apt_get: yes
  retries: 4
  delay: 10

- name: Install essential packages
  ansible.builtin.apt:
    name:
      - nano
      - iptables
      - curl
      - git
    state: present