- name: Initialize Kubernetes
  ansible.builtin.command: sudo kubeadm init
  register: kubeadm_init_result

- name: Create .kube directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Read CA certificate
  ansible.builtin.slurp:
    src: /etc/kubernetes/pki/ca.crt
  register: ca_cert_content

- name: Read admin certificate
  ansible.builtin.slurp:
    src: /etc/kubernetes/pki/admin.crt
  register: admin_cert_content

- name: Read admin key
  ansible.builtin.slurp:
    src: /etc/kubernetes/pki/admin.key
  register: admin_key_content

- name: Set Kubernetes certificate variables
  ansible.builtin.set_fact:
    kubernetes_ca_cert_base64_encoded_content: "{{ ca_cert_content.content | b64decode | b64encode }}"
    kubernetes_admin_cert_base64_encoded_content: "{{ admin_cert_content.content | b64decode | b64encode }}"
    kubernetes_admin_key_base64_encoded_content: "{{ admin_key_content.content | b64decode | b64encode }}"

- name: Assign kube_ca_cert, kube_admin_cert, kube_admin_key variables
  ansible.builtin.set_fact:
    kube_ca_cert: "{{ kubernetes_ca_cert_base64_encoded_content }}"
    kube_admin_cert: "{{ kubernetes_admin_cert_base64_encoded_content }}"
    kube_admin_key: "{{ kubernetes_admin_key_base64_encoded_content }}"

- name: Generate admin.conf from template
  ansible.builtin.template:
    src: templates/kube-config.j2
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  vars:
    kube_server: "{{ hostvars[inventory_hostname]['ansible_host'] }}"  # Replace with your server IP or hostname

- name: Store join command in a fact
  ansible.builtin.set_fact:
    join_command: "{{ kubeadm_init_result.stdout | regex_search('kubeadm join\\s.*\\n\\s*--discovery-token-ca-cert-hash\\s.*') }}"

- name: Save join command to a file
  ansible.builtin.copy:
    content: "{{ join_command }}"
    dest: "/home/{{ ansible_user }}/join_command.txt"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Install Calico CNI plugin
  ansible.builtin.command:
    cmd: kubectl apply -f https://docs.projectcalico.org/v3.16/manifests/calico.yaml
    environment:
      KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
