- name: Kiểm tra trạng thái của các node
  ansible.builtin.shell:
    cmd: kubectl get nodes -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}' | grep -q "False"
  register: nodes_not_ready
  ignore_errors: yes
  changed_when: false

- name: Clone repository Rook
  ansible.builtin.git:
    repo: https://github.com/rook/rook.git
    dest: /home/{{ ansible_user }}/rook
    version: v1.14.6
    single_branch: yes
  when: nodes_not_ready.rc == 1  # Chỉ chạy khi không có node nào đang ở trạng thái NotReady

- name: Khởi tạo rook-ceph operator
  ansible.builtin.shell:
    cmd: kubectl create -f crds.yaml -f common.yaml -f operator.yaml
    chdir: /home/{{ ansible_user }}/rook/deploy/examples
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config
  when: nodes_not_ready.rc == 1  # Chỉ chạy khi không có node nào đang ở trạng thái NotReady

- name: Kiểm tra trạng thái của pod rook-ceph-operator
  ansible.builtin.shell:
    cmd: kubectl get pods -n rook-ceph -l app=rook-ceph-operator -o jsonpath='{.items[0].status.phase}'
  register: operator_status
  retries: 6
  delay: 40
  until: operator_status.stdout == "Running"
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config
  when: nodes_not_ready.rc == 1  # Chỉ chạy khi không có node nào đang ở trạng thái NotReady

- name: Tạo rook-ceph cluster nếu pod rook-ceph-operator đang chạy
  ansible.builtin.command:
    cmd: kubectl create -f cluster.yaml
    chdir: /home/{{ ansible_user }}/rook/deploy/examples
  when: operator_status.stdout == "Running" and nodes_not_ready.rc == 1  # Chỉ chạy khi pod đang chạy và không có node nào đang ở trạng thái NotReady
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config