- name: Turn off swap
  ansible.builtin.command: swapoff -a

- name: Remove swap from fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^\s*(\S+)\s+swap\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)$'
    replace: '#\1 swap \2 \3 \4 \5 \6'

- name: Load kernel modules
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf

- name: Ensure overlay module is loaded
  ansible.builtin.command: modprobe overlay

- name: Ensure br_netfilter module is loaded
  ansible.builtin.command: modprobe br_netfilter

- name: Set kernel parameters for Kubernetes
  ansible.builtin.copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/kubernetes.conf

- name: Apply sysctl parameters without reboot
  ansible.builtin.command: sysctl --system
